---
- name: Check if the system is registered with RHSM
  stat:
    path: "{{ system_cert_file }}"
  register: cert_details
- name: Fail if the certificate is missing
  ansible.builtin.fail:
    msg: "{{ system_cert_file }} missing, please register the system with RHSM"
  when: not cert_details.stat.exists
- name: Install catalog worker
  yum:
    name: "{{ connector_packages }}"
    state: installed
- name: Ensure config directory exists
  file: 
    path: "{{ catalog_config_dir }}"
    recurse: yes
    state: directory
- name: Write Catalog Worker config file
  template:
    dest: "{{ catalog_config_dir }}/catalog.toml"
    mode: 0400
    src: catalog.toml.j2
  when: tower_token | length > 0
- name: Optionally write RHCD config file
  template:
    dest: "{{ rhc_config_dir }}/config.toml"
    mode: 0400
    src: config.toml.j2
  when: mqtt_broker is defined
- name: Start the rhcd systemd service
  systemd:
    unit: rhcd
    enabled: yes
    state: started
